### PR TITLE
Fixed #10352 - remove error if data.length != response['recieved']

### PR DESCRIPTION
**Pull request by shlomizadok**
Needs to be merged also to maint17

### CODE REVIEW

**Comment by ares** [comment]
What does `response.value` do here? it seemed as useless call to me, that's why I'd expect it should be removed

Using puts is not common in Rails, however this is not Rails. I have mixed feelings here, if this code is actually used as a library, I'm not sure we should keep puts there. We should probably rather display debug log on STDOUT in case we run the script from CLI.

**Comment by shlomizadok** [comment]
@ares, I also wasn't sure about ```response.value``` until I read what it really does (raises error if not HTTPSuccess - [doc](http://ruby-doc.org/stdlib-1.9.3/libdoc/net/http/rdoc/Net/HTTPResponse.html#method-i-value) )

As you have said, this is not a Rails app, it's a ruby script. I think we could use either ```puts``` or log to STDOUT. @domcleal, what should be the standard for displaying an error?

**Comment by ares** [comment]
oh wow, could you we please add inline comment for that?

@shlomizadok thie file (lib/smart_proxy_openscap/openscap_lib.rb) is not really a script that user run, I'm not sure if it might be used elsewhere, that's why I'd be in favour of using logger and redirecting this logger to STDOUT in bin/smart-proxy-openscap-send

**Comment by shlomizadok** [comment]
Squashed, rebased, documented and ditched ```puts``` (should one want to see errors, he can look in the log, as this is not intended to run manually usually).
The important part anyhow is https://github.com/OpenSCAP/smart_proxy_openscap/pull/11/files#diff-7b64de0f038ec2dbc5994deb74936428L123 as it there is a diff between sent bytes to received bytes

**Comment by ares** [comment]
visually ACK

**Comment by shlomizadok** [comment]
@isimluk ping?

**Comment by isimluk** [comment]
Merged manually to master and maint branches.

**Comment by shlomizadok** [comment]
@isimluk thanks! 
Merge manually on master as https://github.com/OpenSCAP/smart_proxy_openscap/commit/66f65672db389a4e40ad0d4f22b782929546586e

and on maint-foreman17 as https://github.com/OpenSCAP/smart_proxy_openscap/commit/e646963780f510fd5eeb48820a86ce9a76a9e600

**Pull request closed without merging**
